/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:f81e2227-897a-4a83-ad98-a5a20af75645",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_2iVcsSYHf",
    "aws_user_pools_web_client_id": "5luumi2h2qrb21q1hheve8v8os",
    "oauth": {}
};


export default awsmobile;
